### ISSUE TITLE
Отправка mp3 файла

### ISSUE THREAD

**Issue by NikDevx** [definitio/ha-sox#3]
Добрый вечер
Подскажите, пожалуйста, как отправить mp3 аудио через Home Assistant на динамик робота.

Пытаюсь через автоматизацию, но ничего не происходит.

```
- id: '1619289651813'
  alias: Домофон
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.0x158d00067c192a_switch
    to: single
  condition: []
  action:
  - service: rest_command.doorbell
  - service: shell_command.doorbell_snapshot
  - service: media_player.play_media
    target:
      entity_id: media_player.speaker_roborock
    data:
      media_content_id: http://raspberrypi.local:8123/local/audio/doorbell.mp3
      media_content_type: music
```
